# SPDX-License-Identifier: BSD-3-Clause
SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Stereo speakers"

	EnableSequence [
		cset "name='Amplifier Top Profile Set' Music"
		cset "name='Amplifier Bottom Profile Set' Music"
		cset "name='QUINARY_TDM_RX_0 Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='QUINARY_TDM_RX_0 Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "Speaker"
	}
}

SectionDevice."Mic" {
	Comment "Bottom and top microphones"

	EnableSequence [
		cset "name='DEC0 MODE' ADC_DEFAULT"
		cset "name='DEC1 MODE' ADC_DEFAULT"
		cset "name='ADC1 Switch' 1"
		cset "name='ADC3 Switch' 1"
		cset "name='ADC1_MIXER Switch' 1"
		cset "name='ADC3_MIXER Switch' 1"
		cset "name='TX DEC0 MUX' SWR_MIC"
		cset "name='TX DEC1 MUX' SWR_MIC"
		cset "name='TX SMIC MUX0' SWR_MIC0"
		cset "name='TX SMIC MUX1' SWR_MIC5"
		cset "name='TX_AIF1_CAP Mixer DEC0' 1"
		cset "name='TX_AIF1_CAP Mixer DEC1' 1"
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 0"
		cset "name='TX_AIF1_CAP Mixer DEC0' 0"
		cset "name='TX_AIF1_CAP Mixer DEC1' 0"
		cset "name='TX SMIC MUX0' ZERO"
		cset "name='TX SMIC MUX1' ZERO"
		cset "name='ADC1_MIXER Switch' 0"
		cset "name='ADC3_MIXER Switch' 0"
		cset "name='ADC1 Switch' 0"
		cset "name='ADC3 Switch' 0"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},1"
		CaptureChannels 2
		CaptureMixer "default:${CardId}"
		CaptureMixerElem "Mic"
	}
}
