# SPDX-License-Identifier: BSD-3-Clause
Syntax 4

SectionUseCase."HiFi" {
	File "/Xiaomi/peridot/HiFi.conf"
	Comment "Speakers and built-in microphones"
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"

LibraryConfig.remap.Config {
	ctl.default.map {
		"name='Speaker Playback Volume'" {
			"name='Amplifier Top PCM Playback Volume'".vindex.0 0
			"name='Amplifier Bottom PCM Playback Volume'".vindex.1 0
		}
		"name='Mic Capture Volume'" {
			"name='TX_DEC0 Volume'".vindex.0 0
			"name='TX_DEC1 Volume'".vindex.1 0
		}
	}
}

BootSequence [
	# AudioReach's stream gain is linear Q13; 8192 is unity.
	cset "name='stream0.vol_ctrl0 MultiMedia1 Playback Volu' 8192"
]

FixedBootSequence [
	# Start the amplifiers at -15 dB and both microphones at equal gain.
	cset "name='Amplifier Top PCM Playback Volume' 300"
	cset "name='Amplifier Bottom PCM Playback Volume' 300"
	cset "name='ADC1 Volume' 8"
	cset "name='ADC3 Volume' 8"
	cset "name='TX_DEC0 Volume' 84"
	cset "name='TX_DEC1 Volume' 84"
]
